/* tslint:disable */
/* eslint-disable */
/**
 * Hotel Booking API
 * API для керування готелями та бронюванням номерів.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface Hotel {
    'id'?: number;
    'name': string;
    'address': string;
    'stars'?: number;
}
export interface Room {
    'id'?: number;
    'number': string;
    'type': RoomTypeEnum;
    'price': number;
    'isAvailable'?: boolean;
}

export const RoomTypeEnum = {
    Single: 'Single',
    Double: 'Double',
    Suite: 'Suite',
} as const;

export type RoomTypeEnum = typeof RoomTypeEnum[keyof typeof RoomTypeEnum];


/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Отримати список усіх готелів
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hotelsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/hotels`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Отримати список номерів конкретного готелю
         * @param {number} hotelId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hotelsHotelIdRoomsGet: async (hotelId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'hotelId' is not null or undefined
            assertParamExists('hotelsHotelIdRoomsGet', 'hotelId', hotelId)
            const localVarPath = `/hotels/{hotelId}/rooms`
                .replace('{hotelId}', encodeURIComponent(String(hotelId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Додати новий готель
         * @param {Hotel} hotel 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hotelsPost: async (hotel: Hotel, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'hotel' is not null or undefined
            assertParamExists('hotelsPost', 'hotel', hotel)
            const localVarPath = `/hotels`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(hotel, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Отримати список усіх готелів
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hotelsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Hotel>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hotelsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.hotelsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Отримати список номерів конкретного готелю
         * @param {number} hotelId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hotelsHotelIdRoomsGet(hotelId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hotelsHotelIdRoomsGet(hotelId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.hotelsHotelIdRoomsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Додати новий готель
         * @param {Hotel} hotel 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hotelsPost(hotel: Hotel, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hotelsPost(hotel, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.hotelsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Отримати список усіх готелів
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hotelsGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<Hotel>> {
            return localVarFp.hotelsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Отримати список номерів конкретного готелю
         * @param {number} hotelId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hotelsHotelIdRoomsGet(hotelId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.hotelsHotelIdRoomsGet(hotelId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Додати новий готель
         * @param {Hotel} hotel 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hotelsPost(hotel: Hotel, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.hotelsPost(hotel, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Отримати список усіх готелів
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public hotelsGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).hotelsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Отримати список номерів конкретного готелю
     * @param {number} hotelId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public hotelsHotelIdRoomsGet(hotelId: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).hotelsHotelIdRoomsGet(hotelId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Додати новий готель
     * @param {Hotel} hotel 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public hotelsPost(hotel: Hotel, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).hotelsPost(hotel, options).then((request) => request(this.axios, this.basePath));
    }
}



